[project]
name = "lakera-coding-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.13",
    "huggingface-hub[cli]>=0.33.0",
    "torch>=2.7.1",
    "transformers>=4.52.4",
]
